version: "2.1"
services:

  plasma-deployer:
    image: plasma-deployer:latest
    environment:
      - ETH_CLIENT_HOST=geth
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    healthcheck:
      test: curl plasma-deployer:8000
      interval: 30s
      timeout: 1s
      retries: 5
    depends_on:
      geth:
        condition: service_healthy

  geth:
    image: ethereum/client-go:v1.8.27
    entrypoint: /bin/sh -c "apk add curl && geth --miner.gastarget 7500000 --miner.gasprice "10" --dev --dev.period 1 --rpc --rpcapi personal,web3,eth,net --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcport=8545 --ws --wsaddr 0.0.0.0 --wsorigins='*'"
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8546"
      - "8545"
    healthcheck:
      test: curl geth:8545
      interval: 5s
      timeout: 3s
      retries: 5